# Generated by Django 6.0.7 on 2026-08-04 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('food_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan'), ('OTHER', 'Other')], default='VEG', max_length=20)),
                ('food_category', models.CharField(choices=[('COOKED', 'Cooked Food'), ('PACKAGED', 'Packaged Food'), ('BAKERY', 'Bakery'), ('FRUITS', 'Fruits & Vegetables'), ('OTHER', 'Other')], default='COOKED', max_length=20)),
                ('quantity', models.CharField(max_length=100)),
                ('servings', models.PositiveIntegerField()),
                ('pickup_start_time', models.DateTimeField()),
                ('expiry_time', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
